export enum FieldNames {
	FIRST_NAME = "firstName",
	LAST_NAME = "lastName",
	PHONE = "phone",
	EMAIL = "email",
	PASSWORD = "password",
	CONFIRM_PASSWORD = "confirmPassword",
	TEXT = "text",
	FILE = "file",
	FILES = "files",
	POLICY = "policy",
	CHECKBOX_GROUP = "checkboxGroup",
	CHECKBOX_GROUP_2 = "checkboxGroup2",
	RADIO = "radio",
	SELECT = "select",
	MULTI_SELECT = "multiSelect",
	DATE = "date",
	START_DATE = "startDate",
	END_DATE = "endDate",
	SINGLE_SLIDER = "singleSlider",
	RANGE_SLIDER = "rangeSlider",
}
